### PR TITLE
WIP: make examples work on OSX with 2 devices

### PR DESCRIPTION
**Pull request by tmpvar**
still working through it

refs #58

### CODE REVIEW

**Comment by tmpvar** [comment]
with that last commit the other examples function but there are some visual issues

__fractal__ (opencl on top, cpu on bottom)

screen shot 2015-10-30 at 5 44 40 pm

__plot3__ (opencl on the left, cpu on the right)

screen shot 2015-10-30 at 5 48 15 pm

**Comment by 9prady9** [comment]
@tmpvar Hi, how are these fixes coming along ?

**Comment by tmpvar** [comment]
hey, I think I've taken them as far as I can.  There are some visual differences between cpu and gpu rendering that you might have a better idea of how to fix

**Comment by 9prady9** [comment]
That is fine, what i have noticed is that examples are doing something wrong in terms of compute in forge or at least they have issues on AMD cards. We use forge in ArrayFire and things are rendering in expected manner over there. I will merge your changes now, and will work on fixing the opencl examples later.

Thank you for the fixes.

**Comment by pavanky** [comment]
I have nothing technical to add other than to say they look pretty :+1: :-D

**Pull request merged**
