### PR TITLE
Build fixes for system Freetype and GLM

### PR DESCRIPTION
**Pull request by pavanky**
- This fixes issues on systems where `freetype.h` is located at `freetype2/freetype/freetype.h`

### CODE REVIEW

**Comment by pavanky** [comment]
@9prady9 review pls.

**Comment by 9prady9** [comment]
:+1:

**Comment by pavanky** [comment]
This is in relation to: https://github.com/arrayfire/forge/pull/61

Commenting so that the issues can be linked.

**Comment by pavanky** [comment]
Oops, clicked wrong button by mistake

**Pull request merged**
