### PR TITLE
Compilation fixes for gcc 6.1 + CUDA

### PR DESCRIPTION
**Pull request by pavanky**

### CODE REVIEW

**Comment by 9prady9** [comment]
@pavanky Do we need this change in devel immediately ? otherwise, i will merge it along with other changes (new feature) i have in pipeline, later.

**Comment by pavanky** [comment]
@9prady9 whenever you have time is fine

**Comment by shehzan10** [comment]
Why isn't this going into master? Otherwise to both branches.

**Comment by 9prady9** [comment]
This won't pose any problem while using forge inside ArrayFire. It will be only a problem while using forge CUDA examples. Having it in `devel` should be good enough as of now.

**Pull request merged**
