### PR TITLE
Replace FIND_PACKAGE(GLM) by FIND_PACKAGE(glm). Fixes issue #49.

### PR DESCRIPTION
**Pull request by marbre**

### CODE REVIEW

**Comment by pavanky** [comment]
@shehzan10 Can you test this manually on belle ?

**Comment by pavanky** [comment]
@marbre Is this going to break it for older glm ?

**Comment by marbre** [comment]
@pavanky To be honest, I didn't tested. Give me some minutes and I'll downgrade glm.

**Comment by shehzan10** [comment]
I will be testing both. This change would only effect system GLM. By default we use GLM as an external build.

**Comment by pavanky** [comment]
@shehzan10 I essentially want someone to test this for an older GLM. May be we never supported it properly.

**Comment by marbre** [comment]
@pavanky Just tested with glm-0.9.6.1. In this version a `FindGLM.cmake` module is provided. Thus, `FIND_PACKAGE(GLM REQUIRED)` works fine, but this pull request breaks it.

**Comment by pavanky** [comment]
Can we check for both ? i.e. check both without "REQUIRED" ?
```
FIND_PACKAGE(GLM)
FIND_PACKAGE(glm)
```

and then check if the XXX_FOUND flag is set ?

**Comment by marbre** [comment]
Working on that at the moment..

**Comment by marbre** [comment]
@pavanky This one works for 0.9.6.1 and 0.9.7.1 on my machine.

**Comment by pavanky** [comment]
@marbre The only thing I'd add is a comment saying why both exist. Someone might delete one of those in the future without realizing why they are there.

**Comment by marbre** [comment]
@pavanky That is documented in the issue #49, which is referenced in the commit message ;) Done, added a note.

**Comment by marbre** [comment]
@shehzan10 As a quick check I added 
~~~
    message("${GLM_INCLUDE_DIRS}")
    message("${glm_INCLUDE_DIRS}")
~~~
to the *new* block. `GLM_INCLUDE_DIRS` points to /usr/include, `glm_INCLUDE_DIRS` seems empty.

**Pull request merged**
