### PR TITLE
Use glfw find_package

### PR DESCRIPTION
**Pull request by pfultz2**
This uses glfw's cmake package config, which will build with its exported target. This help build properly when glfw is built statically.

### CODE REVIEW

**Comment by pavanky** [comment]
@pfultz2 can you check which version of cmake the glfw package was introduced ?

**Comment by 9prady9** [comment]
@pfultz2 Also, did you test this change on Windows ?

**Comment by pfultz2** [comment]
> can you check which version of cmake the glfw package was introduced ?

The `glfw3` been there since 3.1, before that the package was called just `glfw`.

**Comment by pfultz2** [comment]
> Also, did you test this change on Windows ?

I did check it on windows and it works for windows as well. I am not sure why it wouldn't.

**Comment by 9prady9** [comment]
Can you please reopen this to be merged into devel. The target branch for new merges is always devel not master.

**Comment by pavanky** [comment]
@9prady9 just cherry pick into devel

**Comment by 9prady9** [comment]
@pavanky The reason i asked him to do it is `CMakeLists.txt` under `src/backend/opengl` is different from the one in master. @pfultz2 I have taken care it for now. Please do open PR's with devel as target branch from now.

**Pull request merged**
