### PR TITLE
Adds support to remove renderables

### PR DESCRIPTION
**Pull request by caseymcc**

### CODE REVIEW

**Comment by 9prady9** [comment]
@caseymcc If you don't mind, can you please rebase from master after #150 is merged and push your additions. Thank you.

**Comment by caseymcc** [comment]
updated

**Comment by 9prady9** [comment]
@caseymcc Can you also please add an example in CPU backend to show case this feature. Thank you.

**Comment by 9prady9** [comment]
@caseymcc Did you get chance to add an example ?

**Comment by 9prady9** [comment]
@caseymcc If you don't mind, I would like to take over this from you and add necessary changes so that this can be merged soon.

**Comment by 9prady9** [comment]
I took the liberty of rebasing this change from latest master. I will try to add an example soon.

**Pull request merged**
