### PR TITLE
Colormap fixes

### LINKED ISSUE #122: Bad colormaps
Colormaps are defined in src/backend/cmap.hpp in sRGB colorspace.

0. Default (gray) colormap is defined by linearly increasing gray values. This linear increase happens in the sRGB colorspace. One should probably use linearly increasing values in a perceptually uniform colorspace so that e.g. 0.8 is perceptually 2x brighter than 0.4. For gray values sRGB is close so it is not a big deal but something better should probably be used.

1. Spectrum. Its name suggests that it represents spectral colors. However pure spectral colors lie outside of the sRGB colorspace (as can be seen from the CIE chromaticity diagram for sRGB) and thus cannot be displayed on most modern monitors. The best thing we can do here is probably to take some interval, e.g. 400nm - 700nm, so that value 0.0 will correspondent to 400nm, 1.0 to 700nm and calculate sRGB colors closest to the spectral ones on this interval. I have not done this but I think that currently specified colormap is nowhere near it (maybe it is, but it must be verified).

2. Colors. Comment says "pure colors" without any clarification of what does it mean. This colormap has different flaws. First of all it is not perceptually uniform, there are almost flat areas interleaved with abrupt changes. Also it contains colors of different brightness even though it looks like it was meant not to.

3. Red. This looks legit.

4. Mood. This looks legit.

5. Heat. It is defined only by 64 points and there is no interpolation between them, this results in a very noticeable banding. It is also highly perceptually non-uniform.
heat

6. Blue. There is an abrupt change in this one near 200.
blue

I suggest to add [colormaps designed for matplotlib](https://bids.github.io/colormap/) and remove of fix others.

It is important to have good colormaps, e.g. when bad colormaps are used in medicine they [can lead to misdiagnosis](http://www.eecs.harvard.edu/~kgajos/papers/2011/borkin11-infoviz.pdf).

### PR DESCRIPTION
**Pull request by 9prady9**
Fixes #122

### CODE REVIEW

**Comment by kryptan** [comment]
To compute sRGB color for a particular wavelength I would used the folllowing method:

1. Calculate coordinates in the [CIE XYZ](https://en.wikipedia.org/wiki/CIE_1931_color_space) colorspace for this wavelength. The method for computing XYZ values from a spectral radiance is [described in Wikipedia](https://en.wikipedia.org/wiki/CIE_1931_color_space#Color_matching_functions). In our case spectral radiance is simply a Dirac delta function centered at the wavelength in question and all these integrals become equal to the color matching functions at this wavelength.

2. [Convert to linear sRGB](https://en.wikipedia.org/wiki/SRGB#The_forward_transformation_.28CIE_xyY_or_CIE_XYZ_to_sRGB.29).

3. At least one of the R, G or B will be negative because this color will be outside of sRGB. The best thing to do here is probably to replace negative values with zero.

Once we've computed linear sRGB colors for each wavelength that we are interested in we need to normalize colors so that they will fit in 0-1 range (i.e. simply divide them by maximum value).

Now we can apply the gamma to these colors get the proper sRGB.

**Comment by kryptan** [comment]
Google directed me to [this weird website](http://cvrl.ioo.ucl.ac.uk/cmfs.htm) for the table values of color matching functions for the standard observer.

That's what I got:

spectrum

The range is 390 - 830 nm.

I used the following Mathematica code to produce the image above.

```Mathematica
fs = Import[
   FileNameJoin[{NotebookDirectory[], "./lin2012xyz2e_5_7sf.csv"}]];
fs = Transpose[fs];
mf = fs[[2 ;; 4]];
srgb = {{3.2406, -1.5372, -0.4986}, {-0.9689, 1.8758, 
      0.0415}, {0.0557, -0.2040, 1.0570}}.mf/2.7;
srgb = Map[Max[0, #] &, srgb, {2}];
srgbNL = Map[#^(1/2.2) &, srgb, {2}];
spectrum = Map[ListInterpolation, srgbNL];
n = 500;
Image[Table[{spectrum[[1]][1 + i*88/n], spectrum[[2]][1 + i*88/n], 
   spectrum[[3]][1 + i*88/n]}, {j, 1, 100}, {i, 0, n}]]
```

**Comment by 9prady9** [comment]
The one i have been referring to is [this](http://www.efg2.com/Lab/ScienceAndEngineering/Spectra.htm) which computes the rgb values for 380nm-780nm range. You can see the range of colors using that code at [this](https://academo.org/demos/wavelength-to-colour-relationship/) page interactively.

**Comment by kryptan** [comment]
Yes, I've read those. The comment in the [original FORTRAN](http://www.physics.sfasu.edu/astro/color/spectra.html) program says:

> The red, green and blue values (RGB) are assumed to vary linearly with wavelength.

But I don't think this is true. There are good mathematical models of human vision and one can precisely calculate sRGB color corresponding to any wavelength or to any combination of wavelengths without such assumptions.

**Comment by 9prady9** [comment]
@kryptan Thank you for the clarification. Took me some time to understand the Mathematica code stub you shared, but was finally able to create the following octave script to generate the visible spectrum colours in sRGB space. I think i got it correct this time, the colormap shows up as expected.

spectrum


```octave
lin2012xyz2e_5_7sf = csvread("lin2012xyz2e_1_7sf.csv");
lambda = transpose(lin2012xyz2e_5_7sf(:,1));
lms = transpose(lin2012xyz2e_5_7sf(:,2:4));
XYZ_to_sRGB = [3.2404542, -1.5371385, -0.4985314;
 -0.9692660, 1.8760108, 0.0415560;
 0.0556434, -0.2040259, 1.0572252];
lrgb = XYZ_to_sRGB * lms;
crgb = lrgb / max(max(lrgb));
crgb = (crgb > 0.0) .* crgb;
bt = (abs(crgb) <= 0.0031308)*12.92.*abs(crgb);
at = (abs(crgb) > 0.0031308).*(1.055*(abs(crgb).^(1/2.4))-0.055);
srgb = bt+at;

wvl_2s = 390:1.72:830;

rInter = spline(lambda, srgb(1, :), wvl_2s);
gInter = spline(lambda, srgb(2, :), wvl_2s);
bInter = spline(lambda, srgb(3, :), wvl_2s);

rgb = [rInter; gInter; bInter];

rgb = (rgb > 0.0) .* rgb;
```

**Comment by 9prady9** [comment]
@arrayfire/core-devel I think this is ready for merge, pls review.

**Comment by shehzan10** [comment]
Looks good to me except for changing Colors->Rainbow. I'm not against rainbow. It's whether changing the enum makes a significant difference to cause problems to users.

**Comment by 9prady9** [comment]
The reason i changed it is to make sense of the colormap that enum value represents. Colors was too generic to describe anything at all.

**Comment by shehzan10** [comment]
> The reason i changed it is to make sense of the colormap that enum value represents. Colors was too generic to describe anything at all.

I understand the reasoning and agree with it. That's why I'm not against the name itself.

**Comment by 9prady9** [comment]
As far as ArrayFire-Forge inter-operation, we should not see any issues as the enum value itself didn't change. Since forge 1.0 is not released, we can change this name without any repercussions.

**Pull request merged**
